### PR TITLE
add username to commands + bugfix

### PR DESCRIPTION
**Pull request by dminko**

### CODE REVIEW

**Comment by dminko** [comment]
Hi - after review please release.

**Comment by jigar-dhulla** [comment]
Thanks for your contributions @dminko. Can I know which version of Signal CLI this is being tested with?

**Comment by dminko** [comment]
Ref.: Eml7454
Date: 15.12.2021 
To: ***@***.***


Re: Re: [jigarakatidus/php-signal] add username to commands + bugfix (PR #5)


Dear Colleagues,

Thanks for the email on 15-Dec 15:55

I tested with CLI version 0.9.2 


Best regards,
Dimitar Minekov
Experta OOD
Tel.: 062 611546
***@***.***

____________________________________________________________________________________
(See the entire email thread) - https://experta.bg/L/T/166971/?m=Qihzcusz#Eml7454 ( https://experta.bg/L/S/166971/m/Qihzcusz )

**Comment by jigar-dhulla** [comment]
Thanks @dminko. I think all methods should be impacted by using Signal CLI 0.9.2. 
This was written keeping signal-cli 0.7.4 in mind.

**Review by jigar-dhulla — APPROVED** [review]

**Pull request merged**
